const ACTIONS = Object.freeze({
  AUTH_USER: 'AUTH_USER',
  ERR: 'ERR',
  FETCH_SERVICES: 'FETCH_SERVICES',
  RESET: 'RESET',
  FETCH_APPOINTMENTS: 'FETCH_APPOINTMENTS',
  CREATE_APPOINTMENT: 'CREATE_APPOINTMENT',
});

export default ACTIONS;
