const ACTIONS = Object.freeze({
  AUTH_USER: 'AUTH_USER',
  AUTH_ERR: 'AUTH_ERR',
  FETCH_SERVICES: 'FETCH_SERVICES',
  SERVICE_ERR: 'SERVICE_ERR',
  RESET_STORE: 'RESET_STORE',
  SERVICE_SELECTED: 'SERVICE_SELECTED',
  CREATE_APPOINTMENT: 'CREATE_APPOINTMENT',
  FETCH_APPOINTMENTS: 'FETCH_APPOINTMENTS',
  APPOINTMENTS_ERR: 'APPOINTMENTS_ERR',
  RESET_SELECTED_SERVICES: 'RESET_SELECTED_SERVICES',
});

export default ACTIONS;
